import './globals.css'
import { Inter } from 'next/font/google';
import Header from './Header';
import { Headerprovider } from '@/components/clientcomponents';
import { Fragment } from 'react';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})



export const metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
  icons: {
    icon: "/img1.jpg"
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Headerprovider>
          <Fragment>
          <Header/>
        {children}
        </Fragment>
        </Headerprovider>
       
        </body>
    </html>
  )
}
